on: [push]

name: run cputest

jobs:
  fox32-run-cputest:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download latest fox32rom artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          repo: fox32-arch/fox32rom
          workflow: fox32rom-unstable.yml
          workflow_conclusion: success

      - name: Download latest cputest artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          repo: fox32-arch/demos
          workflow: demos-unstable.yml
          workflow_conclusion: success

      - name: Move fox32.rom into the root folder
        run: |
          mv fox32.rom/ download/
          cp download/fox32.rom ./fox32.rom

      - name: Install libsdl2-dev and vim
        run: |
          sudo apt update
          sudo apt install -y libsdl2-dev vim

      - name: Build
        run: make

      - name: Test
        run: |
          ./fox32 --headless --rom cputest/cputest.bin | tee cputest.log
          grep 'All tests passed' cputest.log
